### ISSUE TITLE
React group project: set up your Kanban board

### ISSUE THREAD

**Issue by luis-pomare** [luis-pomare/Space-Travelers-Hub#25]
We are 2 people working on this project, here is the link to the project kanban board:
* https://github.com/luis-pomare/Space-Travelers-Hub/projects/1

**Comment by Mihndim2020** [comment]
# STATUS: INVALID!!!  :x: :x: :x: 

Hi Team,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code, please make sure your implement the following changes before you resubmit for review. 

## Required Changes ♻️
_Check the comments below._
- [ ] As it is a requirement for this project, please kindly add information about the number of people working on this project on the issue summary. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by youmari** [comment]
# Project Approved :trophy: :tada: 🟢 

Hi @Mihndim2020 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
